# Generated by Django 5.0.4 on 2024-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
