# Generated by Django 5.0.4 on 2024-06-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='website',
            field=models.URLField(default='', max_length=2000),
        ),
    ]
